---
- hosts: 172.31.36.56
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: copy static files into ansible nodes
    copy:
       src: mytestfile
       dest: /home/ubuntu/mystaticfile
  
  
      