---
# tasks file for mytomcatrole


- include_tasks: myadduser.yml
- include_tasks: installjava.yml
- include_tasks: download.yml
- include_tasks: permission.yml
- include_tasks: tomadminuser.yml
- include_tasks: tomservice.yml
- include_tasks: tomstart.yml